import type { ToolDefinition } from "../contracts";


export const UtilityRegistry: ToolDefinition[] = [
    { id: "pdf-unlock", title: "Remove PDF Password", shortTitle: "Unlock PDF", blurb: "Save an unlocked copy of a PDF you know the password for.", symbol: "lock-open", tint: "#f97316", category: "PDF", command: "unlock_pdf", verification: "unlock-pdf", view: "pdf-unlock", status: "implemented" },
    { id: "pdf-page-numbers", title: "Add PDF Page Numbers", shortTitle: "Page Numbers", blurb: "Stamp page numbers onto a PDF.", symbol: "numbers", tint: "#3b82f6", category: "PDF", command: "add_page_numbers", verification: "pdf-page-numbers", view: "pdf-page-numbers", status: "implemented" },
    { id: "pdf-merge", title: "Merge PDF", shortTitle: "Merge", blurb: "Combine several PDFs into one file.", symbol: "files", tint: "#a855f7", category: "PDF", command: "merge_pdfs", verification: "pdf-merge", view: "pdf-merge", status: "implemented" },
    { id: "pdf-watermark", title: "Watermark PDF", shortTitle: "Watermark", blurb: "Stamp text across PDF pages.", symbol: "droplet", tint: "#06b6d4", category: "PDF", command: "watermark_pdf", verification: "pdf-watermark", view: "pdf-watermark", status: "implemented" },
    { id: "pdf-crop", title: "Crop PDF", shortTitle: "Crop", blurb: "Hide content outside a selected page rectangle.", symbol: "crop", tint: "#10b981", category: "PDF", command: "crop_pdf", verification: "pdf-crop", view: "pdf-crop", status: "implemented" },
    { id: "pdf-protect", title: "Protect PDF", shortTitle: "Protect", blurb: "Add a password so only you can open a PDF.", symbol: "lock", tint: "#ef4444", category: "PDF", command: "protect_pdf", verification: "protect-pdf", view: "pdf-protect", status: "implemented" },
    { id: "images-to-pdf", title: "Images to PDF", shortTitle: "Images to PDF", blurb: "Turn photos and scans into one PDF.", symbol: "photo", tint: "#3b82f6", category: "PDF", command: "images_to_pdf", verification: "images-to-pdf", view: "images-to-pdf", status: "implemented" },
    { id: "pdf-to-images", title: "PDF to Images", shortTitle: "PDF to Images", blurb: "Render PDF pages to JPEG images at 72 to 300 dpi.", symbol: "photo", tint: "#6366f1", category: "PDF", command: "pdf_to_images", verification: "pdf-to-images", view: "pdf-to-images", status: "implemented" },
    { id: "pdf-to-text", title: "PDF to Text", shortTitle: "PDF to Text", blurb: "Extract selectable PDF text into a text file.", symbol: "file-text", tint: "#6b7280", category: "PDF", command: "pdf_to_text", verification: "pdf-to-text", view: "pdf-to-text", status: "implemented" },
    { id: "pdf-split", title: "Split PDF", shortTitle: "Split", blurb: "Break a PDF into separate page files.", symbol: "file-scissors", tint: "#f97316", category: "PDF", command: "split_pdf", verification: "pdf-split", view: "pdf-split", status: "implemented" },
    { id: "pdf-image-extract", title: "Extract Images from PDF", shortTitle: "Extract Images", blurb: "Pull embedded JPEG pictures out at their original resolution.", symbol: "photo-search", tint: "#22c55e", category: "PDF", command: "extract_pdf_images", verification: "pdf-image-extract", view: "pdf-image-extract", status: "implemented" },
    { id: "pdf-sign", title: "Sign PDF", shortTitle: "Sign", blurb: "Place a visible typed signature on a PDF page.", symbol: "signature", tint: "#ec4899", category: "PDF", command: "sign_pdf", verification: "pdf-sign", view: "pdf-sign", status: "implemented" },
    { id: "pdf-ocr", title: "OCR PDF", shortTitle: "OCR", blurb: "Read text out of scans through an offline OCR adapter.", symbol: "scan", tint: "#14b8a6", category: "PDF", command: "ocr_pdf", verification: "pdf-ocr", view: "pdf-ocr", status: "implemented" },
    { id: "pdf-remove-pages", title: "Remove PDF Pages", shortTitle: "Remove Pages", blurb: "Delete selected pages while keeping the rest in order.", symbol: "file-minus", tint: "#92400e", category: "PDF", command: "remove_pdf_pages", verification: "pdf-remove-pages", view: "pdf-remove-pages", status: "implemented" },
    { id: "pdf-extract-pages", title: "Extract PDF Pages", shortTitle: "Extract Pages", blurb: "Pull selected page ranges into a new PDF.", symbol: "file-search", tint: "#6366f1", category: "PDF", command: "extract_pdf_pages", verification: "pdf-extract-pages", view: "pdf-extract-pages", status: "implemented" },
    { id: "pdf-organize", title: "Organize PDF", shortTitle: "Organize", blurb: "Reorder PDF pages and save an organized copy.", symbol: "layout-grid", tint: "#06b6d4", category: "PDF", command: "organize_pdf", verification: "pdf-organize", view: "pdf-organize", status: "implemented" },
    { id: "pdf-compress", title: "Compress PDF", shortTitle: "Compress", blurb: "Shrink PDF stream data without changing page geometry.", symbol: "file-download", tint: "#10b981", category: "PDF", command: "compress_pdf", verification: "pdf-compress", view: "pdf-compress", status: "implemented" },
    { id: "heic-convert", title: "Convert Image Format", shortTitle: "Convert", blurb: "Convert HEIC to PNG, JPEG, WebP, and back.", symbol: "arrows-exchange", tint: "#3b82f6", category: "Images", command: "convert_images", verification: "convert-image-format", view: "image-convert", status: "implemented" },
    { id: "compress", title: "Compress Images", shortTitle: "Compress", blurb: "Shrink image files losslessly or trade quality for size.", symbol: "file-download", tint: "#22c55e", category: "Images", command: "compress_images", verification: "compress-images", view: "image-compress", status: "implemented" },
    { id: "resize", title: "Resize Images", shortTitle: "Resize", blurb: "Scale images to exact dimensions.", symbol: "resize", tint: "#a855f7", category: "Images", command: "resize_images", verification: "resize-images", view: "image-resize", status: "implemented" },
    { id: "rotate", title: "Rotate and Flip Images", shortTitle: "Rotate", blurb: "Rotate images by a right angle.", symbol: "rotate", tint: "#ec4899", category: "Images", command: "rotate_images", verification: "rotate-images", view: "image-rotate", status: "implemented" },
    { id: "crop", title: "Crop Images", shortTitle: "Crop", blurb: "Crop images to a pixel rectangle.", symbol: "crop", tint: "#6366f1", category: "Images", command: "crop_images", verification: "crop-images", view: "image-crop", status: "implemented" },
    { id: "icon-set", title: "Generate App Icons", shortTitle: "Icons", blurb: "Turn one image into a complete app icon set.", symbol: "icons", tint: "#f97316", category: "Images", command: "generate_icon_set", verification: "icon-set", view: "image-icons", status: "implemented" },
    { id: "gif-create", title: "Create GIF", shortTitle: "GIF Maker", blurb: "Animate a batch of still images into a looped GIF.", symbol: "movie", tint: "#14b8a6", category: "Images", command: "create_gif", verification: "gif-create", view: "gif-create", status: "implemented" },
    { id: "gif-extract", title: "Extract GIF Frames", shortTitle: "Frames", blurb: "Split an animated GIF into individual frames.", symbol: "stack-2", tint: "#14b8a6", category: "Images", command: "extract_gif_frames", verification: "gif-extract", view: "gif-extract", status: "implemented" },
    { id: "image-watermark", title: "Watermark Images", shortTitle: "Watermark", blurb: "Apply a visible watermark effect across images.", symbol: "droplet-half", tint: "#06b6d4", category: "Images", command: "watermark_images", verification: "image-watermark", view: "image-watermark", status: "implemented" },
    { id: "image-metadata", title: "Image Metadata", shortTitle: "Metadata", blurb: "Save a copy without image metadata.", symbol: "info-circle", tint: "#10b981", category: "Images", command: "image_metadata", verification: "image-metadata", view: "image-metadata", status: "implemented" },
    { id: "image-tone", title: "Colour and Tone Adjustments", shortTitle: "Tone", blurb: "Adjust image brightness and contrast in batches.", symbol: "adjustments", tint: "#eab308", category: "Images", command: "adjust_image_tone", verification: "image-tone", view: "image-tone", status: "implemented" },
    { id: "tiff-pages", title: "Split and Combine TIFF", shortTitle: "TIFF Pages", blurb: "Process TIFF images without changing the source file.", symbol: "files", tint: "#92400e", category: "Images", command: "process_tiff_pages", verification: "tiff-pages", view: "tiff-pages", status: "implemented" },
    { id: "image-blur-faces", title: "Blur Faces", shortTitle: "Blur Faces", blurb: "Detect and blur faces through an offline vision adapter.", symbol: "face-id", tint: "#ef4444", category: "Images", command: "blur_faces", verification: "image-blur-faces", view: "image-blur-faces", status: "implemented" },
    { id: "image-remove-bg", title: "Remove Background", shortTitle: "Cutout", blurb: "Remove backgrounds through an offline vision adapter.", symbol: "wand", tint: "#a855f7", category: "Images", command: "remove_image_background", verification: "image-remove-bg", view: "image-remove-bg", status: "implemented" },
];

export const utilitiesByCategory = (category: ToolDefinition["category"]) =>
    UtilityRegistry.filter((utility) => utility.category === category);
